spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 9292

management:
  endpoints:
    web:
      exposure:
        include: "*"   # Expose all endpoints — for dev only!
  endpoint:
    health:
      show-details: always   # Show full health details
  info:
    env:
      enabled: true   # Enable environment info

info:
  app:
    name: User Service
    description: Sample Spring Boot User Service with Actuator
    version: 1.0
